name: job5
description: "A new Flutter project."
publish_to: 'none' 


environment:
  sdk: ^3.6.0-36.0.dev


dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  cloud_firestore: ^4.9.1
  shared_preferences: ^2.2.2
  intl: ^0.20.0
  http: ^1.5.0
  cached_network_image: ^3.3.0
  flutter_localizations:
    sdk: flutter 
  lottie: ^2.7.0
  confetti: ^0.7.0
  flutter_animate: ^4.1.1+1
  flutter_staggered_animations: ^1.1.1
  liquid_progress_indicator: ^0.4.0
  connectivity_plus: ^6.1.5
  flutter_secure_storage: ^9.2.4
  camera: ^0.10.0
  path_provider: ^2.0.0
  path: ^1.8.0
  google_generative_ai: ^0.4.7
  fl_chart: ^0.68.0
  flutter_quill: ^8.4.0




  cupertino_icons: ^1.0.8
  get_storage: ^2.1.1
  envied: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
    

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/
    - assets/animations/

